const { find } = require('./exerc/index')
const join = require('./exerc/join')
const map = require('./exerc/map')
const filter = require('./exerc/filter')
const split = require('./exerc/split')
const { wordCamelCase, wordStrOfArray, changeArray, subWord3, newStrWord, joinArray } = require('./exerc/camelCaseDivide')
const firstName = require('./exerc/orderSelectFrstWord')
console.log(join)
console.log(map)
console.log(find)
console.log(filter)
console.log(split)
console.log(wordCamelCase)
console.log(wordStrOfArray)
console.log(changeArray)
console.log(subWord3)
console.log(newStrWord)
console.log(joinArray)
console.log(firstName)
